version: "3.8"
services:
    mongo:
        image: mongo
        container_name: mongodb
        ports: 
            - "27017:27017"
        volumes: 
          - ./database/mongodb/db:/data/db
          - ./database/mongodb/dev.archive:/Databases/dev.archive
          - ./database/mongodb/production:/Databases/production
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
    mongo-express:
       image: mongo-express
       container_name: mongo-express
       environment:
         - ME_CONFIG_MONGODB_ADMINUSERNAME=root
         - ME_CONFIG_MONGODB_ADMINPASSWORD=root
         - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/?authSource=admin
         - ME_CONFIG_BASICAUTH_USERNAME=mexpress
         - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
       ports:
         - "8081:8081"
       links:
         - mongo
volumes: 
    database: {} 
    
networks:
    default: 
        name: mongodb
